CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER DEFAULT 0,
	MEMBER_GENDER NUMBER DEFAULT 3,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;


CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255),
	POST_CONTENT VARCHAR2(255),
	MEMBER_ID VARCHAR2(255),
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);

SELECT *FROM TBL_POST;

CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_NUMBER NUMBER NOT NULL,
	REPLY_CONTENT VARCHAR(255) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	POST_ID NUMBER NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY (POST_ID)
    REFERENCES TBL_REPLY(ID),
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY (MEMBER_ID)
    REFERENCES TBL_MEMBER(ID)
	);

SELECT * FROM TBL_REPLY;
























